FROM python:3.10-bullseye

WORKDIR /app

RUN mkdir -p /app/src/agent/general_nodes \
    && mkdir -p /app/src/agent/specialty_nodes \
    && mkdir -p /app/src/config

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY src/ /app/src/

ENV PYTHONPATH=/app/src

EXPOSE 7860

CMD ["python3", "src/server.py"]